# Generated by Django 3.1.6 on 2021-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_id', models.CharField(max_length=200, verbose_name='id')),
                ('vac_type', models.CharField(max_length=200, verbose_name='type')),
                ('url', models.URLField(verbose_name='url')),
                ('created_at', models.CharField(max_length=200, verbose_name='created at')),
                ('company', models.CharField(max_length=200, verbose_name='company')),
                ('company_url', models.URLField(null=True, verbose_name='company url')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('how_to_apply', models.URLField(verbose_name='how to apply')),
                ('company_logo', models.URLField(null=True, verbose_name='company logo')),
            ],
        ),
    ]
